### ISSUE TITLE
Plot data_latency.py

### ISSUE THREAD

**Issue by FMassin** [yannikbehr/vssc3_scripts#1]
Hi Yannik,

Do you have a code example that read and plot the delays/latencies in data_latency.py ?

Thanks

**Comment by yannikbehr** [comment]
Hi Fred,
Sorry for the late reply. I just committed a [script](https://github.com/yannikbehr/vssc3_scripts/blob/master/analyse_data_latencies.py) to do that.

**Comment by yannikbehr** [comment]
I just saw that it is missing the command line interface. Sorry about that. Are you happy to add that or would you like me to do it?

**Comment by FMassin** [comment]
No I 'm good, and I'll push what I'll come with. Thank you Yannik!
